# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "941768e9067d82000ec449c0bd622ced"
name = "store-currency-format"
handle = "store-currency-format"
application_url = "https://motion-toolbox-inexpensive-loves.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, write_products, read_customers, read_discounts, read_analytics"

[auth]
redirect_urls = ["https://motion-toolbox-inexpensive-loves.trycloudflare.com/auth/callback", "https://motion-toolbox-inexpensive-loves.trycloudflare.com/auth/shopify/callback", "https://motion-toolbox-inexpensive-loves.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
